import Head from 'next/head'
import axios from 'axios'
import { useEffect, useState } from 'react'
import Search from '@/components/Search'
import Weather from '@/components/Weather'
import Unit from '@/components/Unit'
// import { useStateWithCallbackLazy } from 'use-state-with-callback';


export default function Home() {

  const [weatherData, setWeatherData] = useState({})
  const [loading, setLoading] = useState(false)
  const [errorMessage, setErrorMessage] = useState('')
  const [unit, setUnit] = useState('metric')
  const [city, setCity] = useState('');



  const getWeather = (event) => {
    if(event){
      event.preventDefault()
    }
    const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=${unit}&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`
    setLoading(true)

    axios.get(url)
      .then((response) => {
        setWeatherData(response.data)
        setErrorMessage('')
      })
      .catch((error => {
        setErrorMessage('Please enter valid city name')
        console.log(error);
      }))
    setLoading(false)
  }

  useEffect((event)=>{
    if(weatherData.main){
      getWeather(event)
    }
  },[unit])

  
  return (
    <div>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Search getWeather={getWeather} setCity={setCity}/>

      {weatherData.main  && <Unit setUnit={setUnit} getWeather={getWeather} />}

      {loading && <p className='text-center text-white text-xl'>Loading...</p>}

      {!errorMessage && weatherData.main && <Weather weatherData={weatherData} unit={unit} />}

      {errorMessage && <p className='text-xl text-white text-center mt-10 bg-orange-500 p-4'>{errorMessage}</p>}

    </div>
  )
}
