import Head from 'next/head'
import axios from 'axios'
import { useState } from 'react'
import Search from '@/components/Search'
import Weather from '@/components/Weather'


export default function Home() {

  const [city, setCity] = useState('')
  const [weatherData, setWeatherData] = useState({})
  const [loading, setLoading] = useState(false)
  const [errorMessage, setErrorMessage] = useState('')

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=metric&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`

  const getWeather = (event) => {
    event.preventDefault()
    setCity(event.target.cityName.value)
    // setLoading(true)
    console.log(url);
    axios.get(url)
      .then((response) => {
        setWeatherData(response.data)
        console.log(response.data)
      })
      setCity('')
      
    // setLoading(true)
  }

  return (
    <div>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Search getWeather={getWeather}/>

      <Weather weatherData={weatherData}/>

    </div>
  )
}
